language: node_js
dist: trusty
cache:
  directories:
    - "node_modules"
node_js:
    - "10"

addons:
  sonarcloud:
    organization: "hirle-github"
    token:
      secure: "**************************"

script:
  - sonar-scanner